### ISSUE TITLE
外勤—维修统计

### ISSUE THREAD

**Issue by jerrygiser** [jerrygiser/CSZLS#12]
1.管网维修工单明细，里面4个sheet的第二个sheet页面。根据抢维修结束时间超出了要求统计范围的时间段。如图。并格式也需要调整
![11fgcfmm d44c7h iwgmzd](https://cloud.githubusercontent.com/assets/11640202/9241872/d8c9a26e-41ab-11e5-82e3-c8666af3ca01.png)

2.管网维修工单明细，第二个sheet。管道口径、处理结果、使用材料、材料费错位，如图。
![jxwt hg7aw _7gctn v](https://cloud.githubusercontent.com/assets/11640202/9241899/3c6a7c44-41ac-11e5-8084-af06f924888c.png)

**Comment by remotesc2** [comment]
报表这玩意，你看看柯老师有没时间

**Comment by baili666** [comment]
3、第三个sheet页中导出后是空白
4、第四个sheet页中至需要导出100口径以上的管道维修
5、报表的序号出现错乱，从1，0，0，0，2......中间出现0
