### ISSUE TITLE
综合展示系统

### ISSUE THREAD

**Issue by jerrygiser** [jerrygiser/CSZLS#2]
任务管理——GIS错误上报——在街景图标下面添加一个GIS错误上报的快捷图标，因为客户用到的比较多。
![dyv364 lec aj _s y yov](https://cloud.githubusercontent.com/assets/11640202/9188578/8a352278-4010-11e5-8dee-5d5fa86db156.png)

**Comment by remotesc2** [comment]
你在toolbar.xml下的toolbar这个节点里增加一个“GIS错误上报”的节点...
