### ISSUE TITLE
GIS错误上报

### ISSUE THREAD

**Issue by jerrygiser** [jerrygiser/CSZLS#3]
综合展示——任务管理——GIS错误上报。里面的错误信息描述用语言来描述很复杂，加上实际使用过程中是在图上画出标注来使用。所以最好做成如图的形式。
![7qpo nsh3p u 8gol wypb](https://cloud.githubusercontent.com/assets/11640202/9188754/58163b2c-4012-11e5-80ca-5d08cdf404cc.png)

**Comment by remotesc2** [comment]
这是从哪看到的方式。。。
这幅图翻译成文字，是什么意思？

**Comment by jerrygiser** [comment]
这个是X主任提供的，据说是已经实现的标注方式。我们现在GIS错误是用文字来描述嘛。文字描述一是难以描述清楚，二是去现场后根据描述，操作比较难，图片标注的方式更加直观。（当然这个实现不紧急）
![0e usxrgpu 3h nv48wrtkq](https://cloud.githubusercontent.com/assets/11640202/9189724/0e134cd8-401f-11e5-8e3c-f862ed225b39.png)

**Comment by remotesc2** [comment]
我的意思是，主任提供的那个标注图，没看懂~~~

**Comment by jerrygiser** [comment]
我们现在是圈定错误范围嘛，他要的是，你圈定范围，然后在地图上可以用指示框来标明具体的错误，这样方便找问题。示例中的英文内容不必深究。
