### ISSUE TITLE
41.外勤材料管理

### ISSUE THREAD

**Issue by xiongbear** [jerrygiser/CSZLS#52]
外勤材料管理中不能添加新的材料,点击“添加”按钮，只能从下拉的材料中添加已有的材料，无法自己添加新的材料。

**Comment by remotesc2** [comment]
没个错误啥的？

**Comment by xiongbear** [comment]
客户想自己在材料管理中添加新的材料，在BS端实现不了

**Comment by jerrygiser** [comment]
不是bug，是待完善的地方。现在材料管理中，客户新添加的只能是数据库中已有的材料，如果未来客户添加我们数据库中没有的材料，这里就存在问题了。

**Comment by baili666** [comment]
这确实是个bug，之前的材料管理中已经设计了添加功能，但是不能实现添加一类新的设备，这就是有问题的，不仅仅能够运用下拉，还要能够填写新的设备名称。如果说新需求，应该是需要增加批量导入的功能（当然这个就可以往后放放了），添加这个功能bug需要先改
