### ISSUE TITLE
43.关于电脑端工单编辑中的基本信息排列顺序

### ISSUE THREAD

**Issue by xiongbear** [jerrygiser/CSZLS#54]
接单人员：
维修类型：
报修时间：
报修内容：
到达时间：
处理结果：
抢修结束时间：
管径：※
管材：※
损坏程度：※
管道损坏类型：※
损坏原因：※
理赔性质：※
第三方维修：※
承包商：※
承包商负责人：※
水表读数：
管网维修 口径100以上管道 需填选项我用※ 标示  ,具体情况，可以发一个word
“※”并不代表必填，只是起提示作用。

**Comment by remotesc2** [comment]
排序好弄，可以根据元数据findex搞定，这个符号。。。只能另配置了

**Comment by jerrygiser** [comment]
排序调整。。这个符号只是标识，需要填写，不是必填。
![f rj5evg554gu ncc4 fy](https://cloud.githubusercontent.com/assets/11640202/9570914/17d2b4d0-4fc8-11e5-9d55-49f4290af0f4.png)

**Comment by remotesc2** [comment]
你在字段元数据配置下workorder所有字段的findex，就能排序
至于这个标示，好像只能在元数据表里增加字段，否则就得单独写个配置文件

**Comment by jerrygiser** [comment]
行，这个顺序我来调整。至于标注就你来处理吧。
