### ISSUE TITLE
外勤—工单管理—工单查询，查询结果报错。如图

### ISSUE THREAD

**Issue by jerrygiser** [jerrygiser/CSZLS#7]
![a xj8 n l8ntl1 wtp3yf](https://cloud.githubusercontent.com/assets/11640202/9220339/6be186cc-4114-11e5-9436-12e6dba21fd9.png)   搜索条件

**Comment by remotesc2** [comment]
已修正，少了单引号

**Comment by jerrygiser** [comment]
测试通过。
