### ISSUE TITLE
综合展示平台--综合信息--DMA统计图

### ISSUE THREAD

**Issue by baili666** [jerrygiser/CSZLS#77]
C:\Users\baili\AppData\Roaming\Tencent\QQ\Temp(}D0IGZ6@OS{I2%U7XO(}20.png
统计图的抬头应该是不正确的吧，数据应该是当月的计算结果
环比统计图也存在问题，应该是取本月与上月进行对比

**Comment by remotesc2** [comment]
图片没有上传上来。。。
