### ISSUE TITLE
（设计待定）外勤—加班人员录入统计—按照这个表格来做

### ISSUE THREAD

**Issue by jerrygiser** [jerrygiser/CSZLS#8]
![a06924ee53de8a0b71f2c7a18f23ecc9](https://cloud.githubusercontent.com/assets/11640202/9220599/43cd5a56-4116-11e5-9860-8bfaa2ca4926.jpg)

第一列勾选框
第二列全部的维修人员
第三列  【是否加班】  提供两个下拉选项【正常，加班】
第四列【加班倍率】
第五列加班开始时间
第六列加班结束时间
第七列 备注

注意：加班与不加班的行用颜色做区分

**Comment by remotesc2** [comment]
已发给现场，待验证

**Comment by jerrygiser** [comment]
验证通过。
