### ISSUE TITLE
20150917 演示前测出的问题汇总（1）

### ISSUE THREAD

**Issue by baili666** [jerrygiser/CSZLS#80]
1、消火栓的专题图没有
2、综合分析--应急预案，点击预案后弹出
3、防腐点的专题图功能在专题图中拿掉
4、防腐点查询，能够查询防腐点的多媒体照片
5、污水处理厂和污水管网的专题图（现在没有了，要配出来）
6、点击查询天地图缩放的问题
7、管网预警功能出不来
8、运行监测--地图实施监测，要把图例换掉，我来p图，你来换
9、水质监测，转了半天没有显示结果

**Comment by remotesc2** [comment]
1. 姚直接配
2. 我这里能看到应急预案（只不过对应的文件都没了，打开就404）
3. 姚直接配
4. 我来弄（待验收）
5. 以前有过这俩的专题图？如果有数据，姚直接配
6. 我来弄（如果超过最大级别，就不会往回缩放，最大级别现在只能定义为最大-1级）
7. 之前我问过姚，看看字段有没有“维修次数”或者类似字段。。。
8. 我告诉姚路径（待验收）
9. 是不是对方服务又不通了？

**Comment by remotesc2** [comment]
8、搞定
待验收

**Comment by baili666** [comment]
1没有搞定

**Comment by baili666** [comment]
2这个问题不是管网预警，是应急预案，就是那个挂接的文档，查不出来

**Comment by remotesc2** [comment]
是他的markdown语法，写的8，显示成了1

**Comment by remotesc2** [comment]
2、可以看到应急预案，有些文件打不开的，你得看看./map/emerPlan/下头，基本上都空了

**Comment by jerrygiser** [comment]
7.已加维修次数字段，也赋值了部分数据，但是也是没有反应；9.水质监测，后台报错：监测点编号不存在。

**Comment by baili666** [comment]
6、点击查询地图缩放的问题，这个问题没有改彻底，当放大到矢量图那个级别后，进行点击查询，地图会缩到瓦片数据那一级

**Comment by baili666** [comment]
7和9还没有ok。其余都ok
