### ISSUE TITLE
20150917 演示前测出的问题汇总（2）

### ISSUE THREAD

**Issue by baili666** [jerrygiser/CSZLS#81]
10、专题图模块中的专题图能不能改成，我点清除按钮才会清除，哪怕是切换功能也不要清除，我现在想实现比如说我在打开管材专题图的同时，我还想查看维修工单的记录，维修工单和管材专题图能够叠加到一起显示
11、维修养护-维修事件查询，列表中查询出来的记录没有在图上全部显示出来
12、爆管分析，点击关阀搜索后，影响用户数和列表中的不相符（搜索地址：正大建设，供测试）

**Comment by remotesc2** [comment]
10、过
11、待验收
12、待验收
